version: '3.3'

services:
  submitter:
    image: micado/micado-submitter
    container_name: micado-submitter
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/micado/occopus/:/etc/micado/occopus/"
      - "/var/lib/micado/occopus/:/var/lib/micado/occopus/"
    environment:
      #Input template files
      TEMP_AUTH_DATA_FILE: /var/lib/micado/occopus/temp_auth_data.yaml
      TEMP_NODE_DEF_FILE: /var/lib/micado/occopus/temp_node_definitions.yaml
      TEMP_INFRA_DEF_FILE: /var/lib/micado/occopus/temp_infrastructure_descriptor.yaml
      #Input user data files
      USER_DATA_FILE: /var/lib/micado/occopus/temp_user_data.yaml
      #Output occopus descriptors
      AUTH_DATA_FILE: /etc/micado/occopus/auth_data.yaml
      NODE_DEF_FILE: /etc/micado/occopus/nodes/node_definitions.yaml
      INFRA_DEF_FILE: /etc/micado/occopus/infrastructure_descriptor.yaml
      MASTER_IP: $IP
      WORKER_INFRA_NAME: micado_worker_infra
    command: python /app/submitter/submitter.py
  redis:
    image: redis
    container_name: occopus_redis
    volumes:
      - "/var/lib/micado/occopus/redis:/data/"
    command: redis-server --appendonly yes
  occopus:
    depends_on:
      - redis
      - submitter
    image: micado/occopus:1.5
    container_name: occopus
    links:
      - redis
    ports:
      - 5000:5000
    volumes:
      - "/etc/micado/occopus/:/etc/micado/occopus/"
    environment:
      - REDIS_NAME=redis
    command: occopus-rest-service --auth_data_path /etc/micado/occopus/auth_data.yaml --host "$HOST_IP"