global:
  scrape_interval: 1s
  evaluation_interval: 1s
rule_files:
#- 'prometheus.rules'
scrape_configs:
- job_name: job_queuer
  scrape_interval: 5s
  static_configs:
    - targets: ['statsd:9102']

