{
 "title": "JQueuer_Job_Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job_ids_var",
    "label": "Job ID",
    "query": "label_values(jqueuer_job_added,job_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jqueuer_job_accomplished_latency",
     "legendFormat": "{{job_id}}"
    }
   ]
  },
  {
   "title": "[[job_ids_var]]",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "repeat": "job_ids_var",
   "targets": [
    {
     "expr": "jqueuer_job_accomplished_timestamp{job_id='[[job_ids_var]]'}",
     "legendFormat": "Accomplished"
    },
    {
     "expr": "jqueuer_job_started_timestamp{job_id='[[job_ids_var]]'}",
     "legendFormat": "Started"
    },
    {
     "expr": "jqueuer_job_accomplished_latency{job_id='[[job_ids_var]]'}",
     "legendFormat": "Accomplished Latency"
    },
    {
     "expr": "jqueuer_job_failed_timestamp{job_id='[[job_ids_var]]'}",
     "legendFormat": "Failed"
    },
    {
     "expr": "jqueuer_job_failed_latency{job_id='[[job_ids_var]]'}",
     "legendFormat": "Failed - Latency"
    }
   ]
  },
  {
   "title": "[[job_ids_var]] - Task(s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 9 },
   "repeat": "job_ids_var",
   "targets": [
    {
     "expr": "jqueuer_task_started_timestamp{job_id='[[job_ids_var]]'}",
     "legendFormat": "Started"
    },
    {
     "expr": "jqueuer_task_accomplished_timestamp{job_id='[[job_ids_var]]'}",
     "legendFormat": "Accomplished"
    },
    {
     "expr": "jqueuer_task_accomplished_latency{job_id='[[job_ids_var]]'}",
     "legendFormat": "Accomplished - Latency"
    },
    {
     "expr": "jqueuer_task_failed_timestamp{job_id='[[job_ids_var]]'}",
     "legendFormat": "Failed"
    },
    {
     "expr": "jqueuer_task_failed_latency{job_id='[[job_ids_var]]'}",
     "legendFormat": "Failed - Latency"
    }
   ]
  },
  {
   "title": "[[job_ids_var]] - Task Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "repeat": "job_ids_var",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jqueuer_task_accomplished_latency{job_id='[[job_ids_var]]'}",
     "legendFormat": "{{job_id}} - {{task_id}}"
    }
   ]
  }
 ]
}