version: '3'
services:
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
        networks:
            jqueuer_network:

    statsd:
        image: prom/statsd-exporter
        ports:
            - 9125:9125
            - 9125:9125/udp
            - 9102:9102
            - 9102:9102/udp
        networks:
            jqueuer_network:

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - /etc/jqueuer/prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - 9091:9090
        networks:
            jqueuer_network:

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=f4c85f99a0f97a5402e2c0faeefc2355e3df785b62f6254e89074b880a682b19
            - GF_USERS_ALLOW_SIGN_UP=false
        networks:
            jqueuer_network:
        volumes:
            - /etc/jqueuer/grafana/:/etc/grafana/jqueuer
        command:
            - /etc/grafana/jqueuer/install.sh
                

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        networks:
            jqueuer_network:

    experiment_manager:
        image: osabuoun/experiment_manager
        ports:
            - "8081:8081"
        volumes:
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            jqueuer_network:
        volumes:
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
networks:
    jqueuer_network:
        external: true     