version: '3'
services:
    syslog_server:
        image: jumanjiman/rsyslog
        ports:
            - 514:514
            - 514:514/udp
        networks:
            jqueuer_network:

    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
        networks:
            jqueuer_network:
        logging:
            driver: syslog
            options:
                syslog-address: "udp://syslog_server:514"
                log-opt:
                tag: redis

    statsd:
        image: prom/statsd-exporter
        ports:
            - 9125:9125
            - 9125:9125/udp
            - 9102:9102
            - 9102:9102/udp
        networks:
            jqueuer_network:
        logging:
            driver: syslog
            options:
                syslog-address: "udp://syslog_server:514"
                log-opt:
                tag: statsd

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - /etc/jqueuer/prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - 9091:9090
        networks:
            jqueuer_network:
        logging:
            driver: syslog
            options:
                syslog-address: "udp://syslog_server:514"
                log-opt:
                tag: prometheus

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=f4c85f99a0
            - GF_USERS_ALLOW_SIGN_UP=false
        networks:
            jqueuer_network:
        volumes:
            - /etc/jqueuer/grafana/:/etc/grafana/jqueuer
        command:
            - /etc/grafana/jqueuer/install.sh
        logging:
            driver: syslog
            options:
                syslog-address: "udp://syslog_server:514"
                log-opt:
                tag: grafana 

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        networks:
            jqueuer_network:
        logging:
            driver: syslog
            options:
                syslog-address: "udp://syslog_server:514"
                log-opt:
                tag: rabbit

    flower:
        hostname: flower
        image: totem/celery-flower-docker
        ports:
            - "5555:5555"
        networks:
            jqueuer_network:
        volumes:
            - /etc/jqueuer/flower/flowerconfig.py:/opt/celery-flower/flowerconfig.py
            - /etc/jqueuer/celeryconfig.py:/opt/celery-flower/celeryconfig.py
        logging:
            driver: syslog
            options:
                syslog-address: "udp://syslog_server:514"
                tag: flower

    jqueuer_manager:
        image: osabuoun/jqueuer_manager
        ports:
            - "8081:8081"
        volumes:
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            jqueuer_network:
        volumes:
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        logging:
            driver: syslog
            options:
                syslog-address: "udp://syslog_server:514"
                log-opt:
                tag: jqueuer_manager

networks:
    jqueuer_network:
        external: true     